// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ad36e1a5-ab06-4c49-a4ff-b88f347c9714",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_RZMiSZqUa",
    "aws_user_pools_web_client_id": "ojc6j2t4jfnbiv66c5g6te0l8",
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Ingredients",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
